name: 'Send Google Chat messages'
description: 'Send Google Chat messages'
author: '@delivery-much'
branding:
  icon: 'code'
  color: 'yellow'
inputs:
  url:
    description: 'Google Chat Webhook URL'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'